/// COCO 17 human keypoints (nose, eyes, ears, shoulders, elbows, wrists, hips, knees, ankles).
pub const NAMES_COCO_KEYPOINTS_17: [&str; 17] = [
    "nose",
    "left_eye",
    "right_eye",
    "left_ear",
    "right_ear",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
];
