mod bodypart_28;
mod coco_80;
mod coco_91;
mod coco_kpt_17;
mod coco_kpt_halpe_26;
mod coco_kpt_wholebody_133;
mod dota_v1_0_15;
mod dota_v1_5_16;
mod hands_kpt_21;
mod imagenet_1k;
mod object365;
mod picodet_layout;
mod pp_doclayout;
mod ram_tags_en;
mod ram_tags_zh;
mod widerface_kpt_face_5;
mod yolo_doclayout_10;
mod yoloe_4585;

pub use bodypart_28::*;
pub use coco_80::*;
pub use coco_91::*;
pub use coco_kpt_17::*;
pub use coco_kpt_halpe_26::*;
pub use coco_kpt_wholebody_133::*;
pub use dota_v1_0_15::*;
pub use dota_v1_5_16::*;
pub use hands_kpt_21::*;
pub use imagenet_1k::*;
pub use object365::*;
pub use picodet_layout::*;
pub use pp_doclayout::*;
pub use ram_tags_en::*;
pub use ram_tags_zh::*;
pub use widerface_kpt_face_5::*;
pub use yolo_doclayout_10::*;
pub use yoloe_4585::*;
